# https://flakestry.dev/publish
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
jobs:
  publish-flake:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: flakestry/flakestry-publish@main
        with:
          version: "${{ inputs.tag || github.ref_name }}"
